# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = "> 1.0"
  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "3.4.3"
    }
  }
}

