# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  #testing
terraform {
  required_version = "> 1.0"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "2.5.2"
    }
  }
}
